service: data-driven-stubs

plugins:
  - serverless-aws-documentation
  - serverless-offline
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  serverless-offline:
    babelOptions:
      presets: ["es2015"]

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - "s3:*Oject*"
      Resource: arn:aws:s3:::data-driven-test-artefacts

functions:
  utils-get-artefacts:
    handler: functions/artefacts.getTestArtefacts
    events:
      - http:
          path: /utils/artefacts
          method: get
          documentation: 
            summary: "Get Test Artefacts"
            description: "Get Test Artefacts"
            queryParams:
              - name: "filename"
                description: "Test Artefact's Filename"

  utils-upload-artefacts:
    handler: functions/artefacts.uploadTestArtefacts
    events:
      - http:
          path: /utils/artefacts
          method: post
          documentation: 
            summary: "Upload Test Artefacts"
            description: "Upload Test Artefacts"
          

