service: data-driven-stubs

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  serverless-offline:
    babelOptions:
      presets: ["es2015"]

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - "s3:*Oject*"
      Resource: arn:aws:s3:::data-driven-test-artefacts

functions:
  utils-get-artefacts:
    handler: functions/artefacts.getTestArtefacts
    events:
      - http:
          path: /utils/artefacts
          method: get

